version: '3'
services:
  redis: 
    image: redis:alpine
    container_name: sc-redis
    restart: always
    volumes:
      - ./data/redis:/data
    environment:
      - REDIS_PASSWORD=123456
    #command: redis-cli config set requirepass 123456
    networks:
      - sc-net
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:alpine
    container_name: sc-rabbitmq
    restart: always
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    networks:
      - sc-net
    ports:
      - 5672:5672

  postgres:
    image: postgres:9.6-alpine
    container_name: sc-postgres
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql
    networks:
      - sc-net
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres

  apollo-db:
    image: mysql:5.7
    container_name: sc-apollo-db
    restart: always
    networks:
      - sc-net
    ports:
      - 3306:3306
    volumes:
      - ./data/config-server/sql:/docker-entrypoint-initdb.d
      - ./data/mysql:/var/lib/mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root123

  zipkin-server:
    image: openzipkin/zipkin
    container_name: sc-zipkin-server
    restart: always
    volumes:
      - ./data/zipkin-server/logs:/var/logs
    networks:
      - sc-net
    ports:
      - 9411:9411
    environment:
      - RABBIT_ADDRESSES=rabbitmq:5672
      - RABBIT_MQ_PORT=5672
      - RABBIT_PASSWORD=guest
      - RABBIT_USER=guest
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=http://elasticsearch:9200
    depends_on:
      - rabbitmq

  elasticsearch:
    image: elasticsearch:alpine
    container_name: sc-elasticsearch
    restart: always
    environment:
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - node.name=elasticsearch_node_1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elasticsearch/data:/usr/share/elasticsearch/data
      - ./data/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./data/elasticsearch/logs:/usr/share/elasticsearch/logs
    networks:
      - sc-net
    ports:
      - 9200:9200
      - 9300:9300

  skywalking:
    image: wutang/skywalking-docker:5.x
    container_name: skywalking
    privileged: true
    networks:
      - sc-net
    environment:
      - ES_CLUSTER_NAME=elasticsearch
      - ES_ADDRESSES=elasticsearch:9300
      - BIND_HOST=127.0.0.1
      - AGENT_JETTY_BIND_HOST=127.0.0.1
      - NAMING_BIND_HOST=127.0.0.1
      - UI_JETTY_BIND_HOST=0.0.0.0
    depends_on:
      - elasticsearch
    command: ["/wait-for-it.sh", "elasticsearch:9300", "-t", "20"]
    ports:
      - 8080:8080
      - 10800:10800
      - 11800:11800
      - 12800:12800

  kibana:
    image: kibana
    container_name: sc-kibana
    restart: always
    volumes:
      - ./data/kibana/logs:/var/logs/kibana
    networks:
      - sc-net
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  grafana:
    image: grafana/grafana
    container_name: sc-grafana
    restart: always
    volumes:
      - ./data/grafana/logs:/var/logs/grafana
    networks:
      - sc-net
    ports:
      - 3000:3000

networks:
  sc-net:
    external: false