http.host: 0.0.0.0
http.cors.enabled: true
http.cors.allow-origin: "*"
# Uncomment the following lines for a production cluster deployment
#transport.host: 0.0.0.0
#discovery.zen.minimum_master_nodes: 1
transport.host: 0.0.0.0
