server:
  port: 8443

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:8761}/eureka/

spring:
  application:
    name: geteway
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    #password: ${REDIS_PASSWORD:}

  zipkin:
    enabled: true
    sender:
      type: rabbit
  sleuth:
    enabled: true
    http:
      legacy:
        enabled: true
  #jwt密码
  security:
    oauth2:
      jwt:
        signingKey: 123456
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
      - AddResponseHeader=X-Response-Default-Foo, Default-Bar
      - name: RequestRateLimiter
        args:
          redis-rate-limiter.replenishRate: 1  #令牌桶的容积
          redis-rate-limiter.burstCapacity: 1  #流速 每秒
          rate-limiter: "#{@defaultRedisRateLimiter}"  #SPEL表达式去的对应的bean
          key-resolver: "#{@remoteAddressKeyResolver}" #SPEL表达式去的对应的bean
      routes:
      # =====================================
      - id: authorization-server
        uri: lb://authorization-server
        predicates:
        - Path=/authorization-server/**
        filters:
        - PrefixPath=/test-server
        - StripPrefix=2
        - AddResponseHeader=foo, bar
        - name: Retry
          args:
            retries: 3
            statuses: BAD_GATEWAY
#网关白名单，无需要签权url
gate:
  ignore:
    authentication:
      startWith: /oauth,/open

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    com.springboot.cloud.gateway: debug
    com.jalja.org.spring: debug
  path: logs/
  file:
    max-size: 1GB