server:
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:8761}/eureka/

spring:
  application:
    name: authorization-server
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    ##password: ${REDIS_PASSWORD:}
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/spring_cloud
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  zipkin:
    enabled: true
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1.0
  #jwt的密钥
  security:
    oauth2:
      jwt:
        signingKey: 123456

logging:
  level:
    org.springframework.web: debug
    org.springframework.security: DEBUG
    com.springboot.auth: DEBUG
    org.apache.ibatis: debug
    java.sql.PreparedStatement: debug
  path: logs/
  file:
    max-size: 1GB

management:
  endpoints:
    web:
      exposure:
        include: '*'

mybatis:
  configuration:
    map-underscore-to-camel-case: true
