version: '3'
services:
  #MOSS Mysql数据库
  moss-db:
    image: mysql:5.7
    container_name: moss-db
    restart: always
    networks:
      - sc-net
    ports:
      - 3306:3306
    volumes:
      - ./moss/mysql:/docker-entrypoint-initdb.d
      - ./data/mysql:/var/lib/mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root123

  #Moss管理中心
  moss:
    image: w304807481/moss-web:latest
    container_name: moss
    restart: always
    networks:
      - sc-net
    ports:
      - 8086:8086
    env_file: .env-moss
    environment:
      TZ: Asia/Shanghai
    depends_on:
      - moss-db